string(RANDOM LENGTH 12 ALPHABET abcdef0123456789 suffix)
set(root "${TEST_ROOT}/cli-${suffix}")
function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "Command failed (${status}): ${ARGV}\n${output}\n${error}\nFixtures kept in ${root}")
  endif()
  message(STATUS "${output}${error}")
endfunction()
run("${GENERATOR}" --write-fixture "${root}/dataset")
set(config --camera "${root}/dataset/camera.yaml" --imu "${root}/dataset/imu.yaml" --target "${root}/dataset/target.yaml")
run("${CLI}" calibrate --dataset "${root}/dataset" ${config} --output "${root}/fit" --threads 2 --max-time-offset 0.08 --knot-spacing 0.075)
run("${GENERATOR}" --verify-export "${root}/fit/camchain-imucam.yaml")
foreach(report_file calibration-report.pdf residuals.csv residual_summary.json)
  if(NOT EXISTS "${root}/fit/${report_file}")
    message(FATAL_ERROR "Missing calibration diagnostic output: ${report_file}")
  endif()
endforeach()
file(READ "${root}/fit/calibration-report.pdf" pdf_header_hex LIMIT 5 HEX)
if(NOT pdf_header_hex STREQUAL "255044462d")
  message(FATAL_ERROR "Calibration report is not a PDF")
endif()
file(READ "${root}/fit/residuals.csv" residual_csv LIMIT 128)
if(NOT residual_csv MATCHES "timestamp_ns,frame_index,tag_id,corner_id")
  message(FATAL_ERROR "Residual CSV header is invalid")
endif()
file(READ "${root}/fit/residual_summary.json" residual_summary)
string(JSON residual_count GET "${residual_summary}" corner_residuals)
if(residual_count LESS 1)
  message(FATAL_ERROR "Residual summary is empty")
endif()
run("${CLI}" calibrate --cache "${root}/fit/observations.cache" ${config} --output "${root}/cached" --threads 2 --max-time-offset 0.08 --knot-spacing 0.075)
run("${GENERATOR}" --verify-export "${root}/cached/camchain-imucam.yaml")
file(READ "${root}/cached/extraction.json" default_metadata)
string(JSON default_backend GET "${default_metadata}" detector)
if(NOT default_backend STREQUAL "kalibr")
  message(FATAL_ERROR "The default detector is not the historical Kalibr backend")
endif()
# Existing results must never be silently replaced.
execute_process(COMMAND "${CLI}" extract --dataset "${root}/dataset" ${config} --output "${root}/fit"
                RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
if(status EQUAL 0)
  message(FATAL_ERROR "CLI unexpectedly overwrote an existing result directory")
endif()

# Exercise the optional detector through calibration and cache reuse.
run("${CLI}" calibrate --dataset "${root}/dataset" ${config} --detector apriltag3 --output "${root}/apriltag3" --threads 2 --max-time-offset 0.08 --knot-spacing 0.075)
run("${GENERATOR}" --verify-export "${root}/apriltag3/camchain-imucam.yaml")
run("${CLI}" calibrate --cache "${root}/apriltag3/observations.cache" ${config} --output "${root}/apriltag3-cached" --threads 2 --max-time-offset 0.08 --knot-spacing 0.075)
run("${GENERATOR}" --verify-export "${root}/apriltag3-cached/camchain-imucam.yaml")
file(READ "${root}/apriltag3-cached/extraction.json" metadata)
string(JSON backend GET "${metadata}" detector)
if(NOT backend STREQUAL "apriltag3")
  message(FATAL_ERROR "AprilTag 3 detector identity lost when reusing the cache")
endif()
foreach(extra "--detector;apriltag3" "--tag-border;1" "--decimate;2")
  execute_process(COMMAND "${CLI}" calibrate --cache "${root}/apriltag3/observations.cache" ${config} ${extra} --output "${root}/invalid-cache"
                  RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
  if(status EQUAL 0)
    message(FATAL_ERROR "CLI allowed detector settings to override cached observations")
  endif()
endforeach()
