string(RANDOM LENGTH 12 ALPHABET abcdef0123456789 suffix)
set(root "${TEST_ROOT}/cli-${suffix}")
function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "Command failed (${status}): ${ARGV}\n${output}\n${error}\nFixtures kept in ${root}")
  endif()
  message(STATUS "${output}${error}")
endfunction()
run("${GENERATOR}" --write-fixture "${root}/dataset")
set(config --camera "${root}/dataset/camera.yaml" --imu "${root}/dataset/imu.yaml" --target "${root}/dataset/target.yaml")
run("${CLI}" calibrate --dataset "${root}/dataset" ${config} --output "${root}/fit" --threads 2 --max-time-offset 0.08 --knot-spacing 0.075)
run("${GENERATOR}" --verify-export "${root}/fit/camchain-imucam.yaml")
run("${CLI}" calibrate --cache "${root}/fit/observations.cache" ${config} --output "${root}/cached" --threads 2 --max-time-offset 0.08 --knot-spacing 0.075)
run("${GENERATOR}" --verify-export "${root}/cached/camchain-imucam.yaml")
# Existing results must never be silently replaced.
execute_process(COMMAND "${CLI}" extract --dataset "${root}/dataset" ${config} --output "${root}/fit"
                RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
if(status EQUAL 0)
  message(FATAL_ERROR "CLI unexpectedly overwrote an existing result directory")
endif()
